bot_url: "https://t.me/testt_bot_for_dev_bot"

messages:
  responses:
    command_start: "Привет👋🏼! Я буду помогать тебе составлять тренировки, напоминать когда их делать, а так же подводить статистику за определенные промежутки времени :3"
    command_help: "Тут будет текст с информацией по всем командам."
  errors:
    default: "Увы, я не знаю такой команды... :\\"